version: "3"
services:
  go-exercises-worker:
    build: .
    environment:
      MESSAGE_BROKER_ADDRESS: amqp://rabbitmq:rabbitmq@localhost:5672
      ALLOWED_IMPORT_CONFIG: /etc/go-exercises-worker/allowed_imports.json
    command:
      - /usr/local/bin/wait-for-it.sh
      - localhost:5672
      - --
      - /usr/local/bin/go-exercises-worker
    volumes:
      - ./configs:/etc/go-exercises-worker
    network_mode: host

  asyncapi-generator:
    image: asyncapi/generator:1.8.0
    command:
      - --debug
      - --install
      - --output=/app/async-api
      - --force-write
      - /app/async_api.yaml
      - "@asyncapi/html-template"
    volumes:
      - ./docs/async_api.yaml:/app/async_api.yaml
      - ./docs/async-api:/app/async-api

  asyncapi:
    image: nginx:1.21.1-alpine
    ports:
      - 9091:80
    volumes:
      - ./docs/async-api:/usr/share/nginx/html
