// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package queues

import mock "github.com/stretchr/testify/mock"

// MockMessagePublisher is an autogenerated mock type for the MessagePublisher type
type MockMessagePublisher struct {
	mock.Mock
}

// PublishMessage provides a mock function with given fields: queue, messageID, messageData
func (_m *MockMessagePublisher) PublishMessage(queue string, messageID string, messageData interface{}) error {
	ret := _m.Called(queue, messageID, messageData)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, interface{}) error); ok {
		r0 = rf(queue, messageID, messageData)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
