// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package queues

import (
	mock "github.com/stretchr/testify/mock"
	entities "github.com/thewizardplusplus/go-exercises-worker/entities"
)

// MockSolutionRunner is an autogenerated mock type for the SolutionRunner type
type MockSolutionRunner struct {
	mock.Mock
}

// RunSolution provides a mock function with given fields: solution
func (_m *MockSolutionRunner) RunSolution(solution entities.Solution) (entities.Solution, error) {
	ret := _m.Called(solution)

	var r0 entities.Solution
	if rf, ok := ret.Get(0).(func(entities.Solution) entities.Solution); ok {
		r0 = rf(solution)
	} else {
		r0 = ret.Get(0).(entities.Solution)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(entities.Solution) error); ok {
		r1 = rf(solution)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
